---
title: 'Step 3: Store the extracted data'
page-layout: full
---

When you are done with the red list, before it can be uploaded and stored, your designed reviewer peer will have to check it. 

## Steps peer-reviewing sources

You will be given a folder that contains one to many Excel files corresponding to extracted redlists for a given `sourceID`:   

  - Check that the folder name (named after the `sourceID`) matches the `sourceID` in the table of sources_to_extract.    
  - Check that the file names in the folder (corresponding to the redlists) also match the <`sourceID_X`> naming convention.   
  - Check that the other metadata in the sources_to_extract align (e.g., year, title, location, taxa), and if they don't, check if there are any remarks about it in the `extractionRemarks`.    

Go through the Excel files (redlist) one by one. In each sheet check the columns for consistency and try to spot errors:    

  - Check `sourceIdentifier` format.  
  - Check that the `redlistID` corresponds to the file name (i.e., that `111_1` is not `111_3` in the file).  
  - Check that all the Zotero citations for the source have been created.   
  - Check that the `statusMappingID` used in the redlist matches the correct one in the status mapping table.   
  - Detect any line breaks or double-spaces.    
  - Check that lists are properly structured: " | " (with spaces).  
  - Check that there are no other technical errors, such as hyperlinks (we don't want them), colours being used, hidden rows, extra columns, and comments on fields.    
  - Check that the controlled vocabulary is used properly, and no free text is used in the **CV** fields.   
  - Check general inconsistencies (e.g. if `sourceType` is a collection, then `sourceFormat` should be multiple).   

  
## Finalising a source

Amend all the changes suggested by your peer.   
Once you are done with all the corrections, finalise your source by storing the folder in the folder [[tetrapods_extracted_sources](https://czuvpraze.sharepoint.com/:f:/r/teams/czu-in19b7pkjs2ctzgp-Gainsandlosses/Sdilene%20dokumenty/RegRed/data/tetrapods_extracted_sources?csf=1&web=1&e=bx6Zki)]{colour="#fff" bg-colour="#3169e0"} and marking `done` in the `progress` column of the file [[tetrapods_sources_to_extract](https://czuvpraze.sharepoint.com/:x:/r/teams/czu-in19b7pkjs2ctzgp-Gainsandlosses/Sdilene%20dokumenty/RegRed/data/regred_tetrapods_sources_to_extract.xlsx?d=wf0ea428dc8d944aa8129214a38f69238&csf=1&web=1&e=UXEtEO)]{colour="#fff" bg-colour="#31b0e0"}.  